version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - django_skillbox.wsgi:application
      - --bind
      - "0.0.0.0:8080"
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./django_skillbox/database:/app/database

#  grafana:
#    image: grafana/grafana:9.2.15
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
#    logging:
#      driver: loki
#      options:
##         loki-url: http://host.docker.internal:3100/loki/api/v1/push
#          loki-url: http://localhost:3100/loki/api/v1/push
#
#  loki:
#    image: grafana/loki:2.8.0
#    ports:
#      - "3100:3100"
