# Generated by Django 5.0 on 2024-02-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
